### PR TITLE
added check for valid email

### PR DESCRIPTION
**Pull request by hakasapl**
If users specify incorrect email or do not include email, this catches that and prevents an invalid email from spamming the SMTP server.

### CODE REVIEW

**Comment by neilmunday** [comment]
@hakasapl thank you for the suggestion. I think it might be better to make this a configuration option, e.g. "enableEmailCheck" because for some sites it is valid to say have a mail option of "userX" as the cluster's mail set-up translates this into a mailbox delivery.

**Comment by hakasapl** [comment]
Makes sense, I will revise the PR soon.

- Hakan

**Comment by neilmunday** [comment]
@hakasapl thank for the suggestion, I have implemented in the 3.0 branch which will be merged soon into main for a new release.

**Comment by neilmunday** [comment]
Version 3.0 released.

**Pull request closed without merging**
